name: Android CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Copy environment variables
        env:
          OSS_SONATYPE_NEXUS_USERNAME: ${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}
          OSS_SONATYPE_NEXUS_PASSWORD: ${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}
          SECRET_KEY_RING_FILE_BASE_64: ${{ secrets.SECRET_KEY_RING_FILE_BASE_64 }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./.github/scripts/copy_env_variables.sh

      - name: Build with Gradle
        run: ./gradlew build test check

      - name: Upload snapshot archives
        run: ./.github/scripts/deploy_snapshot.sh
